/**
 * Home page — landing dashboard with overview of all modules.
 */

import { t } from '../shared/i18n';
import type { SupportedLanguage } from '../shared/types';
import { Link } from 'react-router-dom';

interface Props {
  language: SupportedLanguage;
}

const modules = [
  { path: '/crowd', icon: '👥', key: 'nav.crowd', desc: 'Real-time crowd density monitoring with AI congestion prediction.' },
  { path: '/navigation', icon: '🗺️', key: 'nav.navigation', desc: 'AI-powered turn-by-turn indoor navigation assistance.' },
  { path: '/chat', icon: '💬', key: 'nav.chat', desc: 'Multilingual chat assistant for fan support in 5 languages.' },
  { path: '/sustainability', icon: '🌱', key: 'nav.sustainability', desc: 'Waste, carbon, and transport intelligence dashboard.' },
  { path: '/control-room', icon: '🛡️', key: 'nav.controlRoom', desc: 'AI-powered incident management for stadium staff.' },
  { path: '/operations', icon: '📊', key: 'nav.operations', desc: 'Daily operational briefing generated by AI.' },
];

export default function HomePage({ language }: Props) {
  return (
    <div>
      <header className="page-header">
        <h1 className="page-title">{t('app.title', language)}</h1>
        <p className="page-subtitle">{t('app.subtitle', language)} — GenAI-Powered Stadium Operations Platform</p>
      </header>

      <div className="grid grid-3" style={{ marginBottom: 'var(--space-xl)' }}>
        <div className="stat-card">
          <div className="stat-label">Stadium Capacity</div>
          <div className="stat-value">67,000</div>
          <div className="stat-change positive">FIFA World Cup 2026</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Active Modules</div>
          <div className="stat-value">6</div>
          <div className="stat-change positive">All systems operational</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Languages Supported</div>
          <div className="stat-value">5</div>
          <div className="stat-change positive">EN · ES · PT · FR · AR</div>
        </div>
      </div>

      <h2 style={{ fontSize: 'var(--font-size-xl)', fontWeight: 700, marginBottom: 'var(--space-lg)', position: 'relative', zIndex: 1 }}>
        Platform Modules
      </h2>

      <div className="grid grid-2">
        {modules.map((mod) => (
          <Link key={mod.path} to={mod.path} style={{ textDecoration: 'none' }}>
            <div className="card" role="article">
              <div className="card-header">
                <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-sm)' }}>
                  <span style={{ fontSize: '1.5rem' }} aria-hidden="true">{mod.icon}</span>
                  <h3 className="card-title">{t(mod.key, language)}</h3>
                </div>
                <span style={{ color: 'var(--accent-primary)', fontSize: 'var(--font-size-sm)' }}>→</span>
              </div>
              <p style={{ color: 'var(--text-secondary)', fontSize: 'var(--font-size-sm)' }}>
                {mod.desc}
              </p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
